export class Offers {
    public id?: string
    public oferta: number
    public licitacion: string
    public licitacion_id: string
    public usuario: string
    public email: string
    public proveedor: number
    public provenom: string
    public fecha: string
    public finaliza?: number
    public producto: number
    public descrip: string
    public cantidad: number
    public unidad: string
    public costo: number
    public precio: number
    public incoterm: string
    public entrega: number
    public estado: number
    public detalle: string
    public scoreProveedor: number
    public scorePrecio: number
    public scoreEntrega: number
    public scoreCantidad: number
    public scoring: number 
    public financiacion: number
    public scoreFinanciacion: number
    public scoreRanking: number
    public precioPesos: number
    public cotizacion: number
    public desempeno: number
}