export class Suppliers {
    public id?: string
    public codigo: number
    public nombre: string
    public usuario: string
    public domicilio: string
    public telefono: string
    public c_postal: number
    public localidad: string
    public provincia: string
    public pais: string
    public desempeno: number
    public ultcompra: string
    public upload: object
    public activo: boolean
    public cuentacbu: string
    public fantasia: string
    public actividad: string
    public correspondencia: string
    public CUIT: string
    public IIBB: string
    public retIIBBSF: boolean
    public aliretIIBBSF: number
    public motiexenIIBBSF: string
    public retIIBBMI: boolean
    public aliretIIBBMI: number
    public motiexenIIBBMI: string
    public retGAN: boolean
    public aliretGAN: number
    public motiexenGAN: string 
}